# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-08 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='期')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Course', verbose_name='课程')),
                ('teachers', models.ManyToManyField(to='study.User', verbose_name='老师')),
            ],
        ),
    ]
