# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-08 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_classlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassList',
            new_name='Class',
        ),
    ]
