# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-08 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20181108_2233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='ClassList',
        ),
    ]
